services:
  wled-album-art:
    build: .
    container_name: wled-album-art
    ports:
      - "3080:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    network_mode: bridge
